package ${packageName};

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.lang.Opt;
import cn.hutool.core.util.StrUtil;
import com.baomidou.mybatisplus.core.toolkit.support.SFunction;
import com.c332030.ctool4j.core.util.CList;
import com.c332030.ctool4j.core.util.CMap;
import com.c332030.ctool4j.core.util.CCollUtils;
import com.c332030.ctool4j.mybatisplus.service.ICService;
import com.c332030.ctool4j.definition.function.CBiFunction;
import com.c332030.ctool4j.definition.function.CFunction;
import ${entityFullName};
import lombok.val;

import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * <p>Description: ${serviceName}</p>
 * <p>Auto-generated by @CAutoBizService</p>
 * @since auto-generated
 */
public interface ${serviceName}<ENTITY extends ${entityName}> extends ICService<ENTITY> {

    default ENTITY getBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) {
            return null;
        }
        return lambdaQuery()
            .eq(${entityName}::get${BizIdCapital}, ${bizIdField})
            .one();
    }

    default ENTITY getBy${BizIdCapital}(${entityName} entity) {
        if(Objects.isNull(entity)) {
            return null;
        }
        return getBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default Opt<ENTITY> getBy${BizIdCapital}Opt(String ${bizIdField}) {
        return Opt.ofNullable(getBy${BizIdCapital}(${bizIdField}));
    }

    default Opt<ENTITY> getBy${BizIdCapital}Opt(${entityName} entity) {
        return Opt.ofNullable(getBy${BizIdCapital}(entity));
    }

    default List<ENTITY> listBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) {
            return CList.of();
        }
        return lambdaQuery()
            .eq(${entityName}::get${BizIdCapital}, ${bizIdField})
            .list();
    }

    default List<ENTITY> listBy${BizIdCapital}(${entityName} entity) {
        if(null == entity) {
            return CList.of();
        }
        return listBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default Long countBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) {
            return 0L;
        }
        return lambdaQuery()
            .eq(${entityName}::get${BizIdCapital}, ${bizIdField})
            .count()
            .longValue();
    }

    default Long countBy${BizIdCapital}(${entityName} entity) {
        if(entity == null) {
            return 0L;
        }
        return countBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default boolean updateBy${BizIdCapital}(${entityName} entity) {
        if(Objects.isNull(entity)) {
            return false;
        }
        return updateById(entity);
    }

    default boolean removeBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) {
            return false;
        }
        return lambdaUpdate()
            .eq(${entityName}get${BizIdCapital}, ${bizIdField})
            .remove();
    }

    default boolean removeBy${BizIdCapital}(${entityName} entity) {
        if(null == entity) {
            return false;
        }
        return removeBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default List<ENTITY> listBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) {
            return CList.of();
        }
        return lambdaQuery()
                .in(${entityName}::get${BizIdCapital}, ${bizIdField}s)
                .list();
    }

    default List<ENTITY> listBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) {
            return CList.of();
        }
        val ${bizIdField}s = CCollUtils.convert(entityList, ${entityName}::get${BizIdCapital});
        return listBy${BizIdCapital}s(${bizIdField}s);
    }

    default Long countBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) {
            return 0L;
        }
        return lambdaQuery()
            .in(${entityName}::get${BizIdCapital}, ${bizIdField}s)
            .count()
            .longValue();
    }

    default Long countBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) {
            return 0L;
        }
        val ${bizIdField}s = CCollUtils.convert(entityList, ${entityName}::get${BizIdCapital});
        return countBy${BizIdCapital}s(${bizIdField}s);
    }

    default boolean removeBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) {
            return false;
        }
        return lambdaUpdate()
            .in(${entityName}get${BizIdCapital}, ${bizIdField}s)
            .remove();
    }

    default boolean removeBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) {
            return false;
        }
        val ${bizIdField}s = CCollUtils.convert(entityList, ${entityName}::get${BizIdCapital});
        return removeBy${BizIdCapital}s(${bizIdField}s);
    }

    default Map<String, ENTITY> listMapBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) {
            return CMap.of();
        }
        val entities = listBy${BizIdCapital}s(${bizIdField}s);
        return CCollUtils.toMap(entities, ${entityName}get${BizIdCapital});
    }

    default Map<String, ENTITY> listMapBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) {
            return CMap.of();
        }
        val ${bizIdField}s = CCollUtils.convert(entityList, ${entityName}::get${BizIdCapital});
        return listMapBy${BizIdCapital}s(${bizIdField}s);
    }

    default Map<String, List<ENTITY>> listGroupMapBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) {
            return CMap.of();
        }
        return listBy${BizIdCapital}s(${bizIdField}s).stream()
            .collect(Collectors.groupingBy(${entityName}get${BizIdCapital}));
    }

}
