package ${packageName};

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.lang.Opt;
import cn.hutool.core.util.StrUtil;
import com.baomidou.mybatisplus.core.toolkit.support.SFunction;
import com.c332030.ctool4j.core.util.CList;
import com.c332030.ctool4j.core.util.CMap;
import com.c332030.ctool4j.mybatisplus.service.ICService;
import ${entityFullName};
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * <p>Description: ${serviceName}</p>
 * <p>Auto-generated by @AutoBizService</p>
 * @since auto-generated
 */
public interface ${serviceName} extends ICService<${entityName}> {

    default SFunction<${entityName}, String> get${BizIdCapital}Column() {
        return ${entityName}::get${BizIdCapital};
    }

    default ${entityName} getBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) { return null; }
        return lambdaQuery().eq(get${BizIdCapital}Column(), ${bizIdField}).one();
    }

    default ${entityName} getBy${BizIdCapital}(${entityName} entity) {
        if(Objects.isNull(entity)) { return null; }
        return getBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default Opt<${entityName}> getBy${BizIdCapital}Opt(String ${bizIdField}) {
        return Opt.ofNullable(getBy${BizIdCapital}(${bizIdField}));
    }

    default Opt<${entityName}> getBy${BizIdCapital}Opt(${entityName} entity) {
        return Opt.ofNullable(getBy${BizIdCapital}(entity));
    }

    default List<${entityName}> listBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) { return CList.of(); }
        return lambdaQuery().eq(get${BizIdCapital}Column(), ${bizIdField}).list();
    }

    default List<${entityName}> listBy${BizIdCapital}(${entityName} entity) {
        if(null == entity) { return CList.of(); }
        return listBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default Long countBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) { return 0L; }
        return lambdaQuery().eq(get${BizIdCapital}Column(), ${bizIdField}).count();
    }

    default Long countBy${BizIdCapital}(${entityName} entity) {
        if(entity == null) { return 0L; }
        return countBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default boolean updateBy${BizIdCapital}(${entityName} entity) {
        if(Objects.isNull(entity)) { return false; }
        return updateById(entity);
    }

    default boolean removeBy${BizIdCapital}(String ${bizIdField}) {
        if(StrUtil.isBlank(${bizIdField})) { return false; }
        return lambdaUpdate().eq(get${BizIdCapital}Column(), ${bizIdField}).remove();
    }

    default boolean removeBy${BizIdCapital}(${entityName} entity) {
        if(null == entity) { return false; }
        return removeBy${BizIdCapital}(entity.get${BizIdCapital}());
    }

    default List<${entityName}> listBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) { return CList.of(); }
        return lambdaQuery().in(get${BizIdCapital}Column(), ${bizIdField}s).list();
    }

    default List<${entityName}> listBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) { return CList.of(); }
        List<String> ${bizIdField}s = CList.of(entityList.stream().map(e -> e.get${BizIdCapital}()).toArray(String[]::new));
        return listBy${BizIdCapital}s(${bizIdField}s);
    }

    default Long countBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) { return 0L; }
        return lambdaQuery().in(get${BizIdCapital}Column(), ${bizIdField}s).count();
    }

    default Long countBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) { return 0L; }
        List<String> ${bizIdField}s = CList.of(entityList.stream().map(e -> e.get${BizIdCapital}()).toArray(String[]::new));
        return countBy${BizIdCapital}s(${bizIdField}s);
    }

    default boolean removeBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) { return false; }
        return lambdaUpdate().in(get${BizIdCapital}Column(), ${bizIdField}s).remove();
    }

    default boolean removeBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) { return false; }
        List<String> ${bizIdField}s = CList.of(entityList.stream().map(e -> e.get${BizIdCapital}()).toArray(String[]::new));
        return removeBy${BizIdCapital}s(${bizIdField}s);
    }

    default Map<String, ${entityName}> listMapBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) { return CMap.of(); }
        SFunction<${entityName}, String> column = get${BizIdCapital}Column();
        return listBy${BizIdCapital}s(${bizIdField}s).stream()
            .collect(java.util.stream.Collectors.toMap(column, e -> e, (a, b) -> a));
    }

    default Map<String, ${entityName}> listMapBy${BizIdCapital}s(List<? extends ${entityName}> entityList) {
        if(CollUtil.isEmpty(entityList)) { return CMap.of(); }
        List<String> ${bizIdField}s = CList.of(entityList.stream().map(e -> e.get${BizIdCapital}()).toArray(String[]::new));
        return listMapBy${BizIdCapital}s(${bizIdField}s);
    }

    default Map<String, List<${entityName}>> listGroupMapBy${BizIdCapital}s(Collection<String> ${bizIdField}s) {
        if(CollUtil.isEmpty(${bizIdField}s)) { return CMap.of(); }
        SFunction<${entityName}, String> column = get${BizIdCapital}Column();
        return listBy${BizIdCapital}s(${bizIdField}s).stream()
            .collect(java.util.stream.Collectors.groupingBy(column));
    }

}
