package ${packageName};

import org.springframework.stereotype.Component;
${imports}

/**
 * <p>Description: ${initClassName}</p>
 * <p>Auto-generated by @CAutowiredScan</p>
 * @since auto-generated
 */
@Component
public class ${initClassName} {

    public ${initClassName}(${constructorParams}) {
        ${constructorAssignments}
    }

}
