package com.c332030.ctool4j.spring.processor;

import com.c332030.ctool4j.base.processor.CAbstractProcessor;
import com.c332030.ctool4j.spring.annotation.CAutowired;
import lombok.val;

import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * <p>
 * Description: CAutowiredScanProcessor
 * </p>
 * <p>
 * 注解处理器：扫描标注 {@code CAutowiredScan} 的类，为其中标注 {@code CAutowired} 的字段生成构造器注入的 Init 类。
 * </p>
 *
 * <h2>能力目录</h2>
 * <p>{@code CAutowiredScanProcessor}：自动注入扫描处理器，编译期生成注入代码。</p>
 * <ul>
 *   <li>生成 {@code {类名}Init}：为标注 {@code CAutowiredScan} 的类生成构造器注入的 Spring 组件。</li>
 *   <li>类型名归一：泛型/数组字段拆分为完整类名逐一 import，构造器参数取简单名。</li>
 * </ul>
 *
 * <h2>设计要点</h2>
 * <ul>
 *   <li><b>模板内联</b>：生成代码的模板以类内常量 {@code TEMPLATE} 持有，不读取任何 classpath 资源。
 *   注解处理器在编译期运行，资源可能位于 processorpath / classpath / 模块层等不同位置；一旦读取失败，
 *   构建结果会随「处理器由谁装载、资源可见性如何」而漂移（并行构建下更易暴露），
 *   因此本处理器不依赖任何外部资源。</li>
 *   <li>字段筛选：仅取标注 {@code CAutowired} 的字段，字段在类内声明顺序即构造器参数顺序。</li>
 *   <li>生成结果通过 {@code Filer.createSourceFile} 输出，第二个参数传被注解的类元素，使生成类与业务类
 *   保持同一「发起类型」关系，在语义上归属于业务类所属模块，IDE 增量编译与 Maven 增量编译都能稳定生效。</li>
 * </ul>
 *
 * <h2>兜底设计</h2>
 * <table border="1">
 *   <caption>兜底行为</caption>
 *   <tr>
 *     <th>场景</th>
 *     <th>兜底行为</th>
 *   </tr>
 *   <tr>
 *     <td>被注解类无 {@code CAutowired} 字段</td>
 *     <td>输出 {@code WARNING} 诊断并跳过，不生成空注入类</td>
 *   </tr>
 *   <tr>
 *     <td>源码文件写出失败（{@link IOException}）</td>
 *     <td>输出 {@code ERROR} 诊断（中断构建），不静默吞掉</td>
 *   </tr>
 * </table>
 *
 * <h2>适用范围</h2>
 * <ul>
 *   <li>编译期自动注入生成，配合 {@code CAutowiredScan} 声明扫描入口。</li>
 * </ul>
 *
 * <h2>不适用与边界场景</h2>
 * <ul>
 *   <li>仅支持 Java 8 及以上的源码版本。</li>

 * </ul>
 *
 * <h2>已知限制与取舍</h2>
 * <ul>
 *   <li>不支持嵌套类：被注解类若为嵌套类，生成类会与外部类同名冲突，需避免在嵌套类上使用。</li>
 *   <li>不支持同包同名类的重复生成（同一次编译内文件名冲突将由 {@code Filer} 报错）。</li>
 * </ul>
 *
 * @since 2026/5/17
 * @version 1.0
 */
@SupportedAnnotationTypes("com.c332030.ctool4j.spring.annotation.CAutowiredScan")
public class CAutowiredScanProcessor extends CAbstractProcessor {

    /**
     * 生成类模板（占位符由 {@link #render} 替换）
     *
     * <p>刻意内联为常量而非 classpath 资源：编译期注解处理器的资源可见性取决于装载路径，
     * 读取外部资源会造成构建结果不稳定，详见类级「设计要点」。</p>
     */
    private static final String TEMPLATE =
            "package ${packageName};\n"
            + "\n"
            + "import org.springframework.stereotype.Component;\n"
            + "${imports}"
            + "\n"
            + "/**\n"
            + " * <p>Description: ${initClassName}</p>\n"
            + " * <p>Auto-generated by @CAutowiredScan</p>\n"
            + " * @since auto-generated\n"
            + " */\n"
            + "@Component\n"
            + "public class ${initClassName} {\n"
            + "\n"
            + "    public ${initClassName}(\n"
            + "        ${constructorParams}\n"
            + "    ) {\n"
            + "        ${constructorAssignments}\n"
            + "    }\n"
            + "\n"
            + "}\n";

    /**
     * 处理注解：为标注 CAutowiredScan 的类生成 Init 类
     *
     * @param annotations 注解集合
     * @param roundEnv    轮次环境
     * @return true
     */
    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (val annotation : annotations) {
            for (val element : roundEnv.getElementsAnnotatedWith(annotation)) {
                if (element.getKind() == ElementKind.CLASS) {
                    TypeElement classElement = (TypeElement) element;
                    generateInitClass(classElement);
                }
            }
        }
        return true;
    }

    /**
     * 为被注解类生成构造器注入的 {@code {类名}Init} 源文件
     *
     * <p><b>详细步骤</b>：</p>
     * <ol>
     *   <li>收集类内标注 {@code CAutowired} 的字段；无字段时输出 {@code WARNING} 并跳过；</li>
     *   <li>按字段声明顺序生成构造器参数（类型取简单名）与赋值语句（调用对应的静态 setter）；</li>
     *   <li>汇总 import：业务类自身 + 各字段泛型/数组展开后的完整类名（去重、去 {@code java.lang.*}）；</li>
     *   <li>以 {@code Filer.createSourceFile} 写出，第二个参数传被注解类元素以保持同一「发起类型」。</li>
     * </ol>
     *
     * <p><b>边界与已知限制</b>：不支持嵌套类（生成类会与外部类同名冲突）；
     * 写出失败时输出 {@code ERROR} 诊断中断构建，不静默吞掉。</p>
     *
     * @param classElement 被注解的类元素
     */
    private void generateInitClass(TypeElement classElement) {
        val autowiredFields = findAutowiredFields(classElement);
        if (autowiredFields.isEmpty()) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING,
                    "No CAutowired fields found in " + classElement.getQualifiedName());
            return;
        }

        val className = classElement.getSimpleName().toString();
        val classPackage = getPackageName(classElement);
        val classFullName = classElement.getQualifiedName().toString();

        val initClassName = className + "Init";
        val initClassPackage = classPackage;
        val initClassFullName = initClassPackage + "." + initClassName;

        val constructorParams = autowiredFields.stream()
                .map(f -> toSimpleType(f.fieldType) + " " + f.fieldName)
                .collect(Collectors.joining(",\n        "))
                ;

        val constructorAssignments = autowiredFields.stream()
                .map(f -> className + ".set" + capitalize(f.fieldName) + "(" + f.fieldName + ");")
                .collect(Collectors.joining("\n        "));

        // 泛型/数组字段须拆出内部完整类名逐一 import（如 java.util.List<com.xxx.Xxx> 需 import 两者），
        // 不能直接 import 整个类型字符串（java.util.List<com.xxx.Xxx> 是非法 import）
        val imports = new StringBuilder();
        imports.append("import ").append(classFullName).append(";\n");
        autowiredFields.stream()
                .flatMap(field -> extractFullClassNames(field.fieldType).stream())
                .distinct()
                .filter(importName -> !importName.startsWith("java.lang."))
                .filter(importName -> !importName.equals(classFullName))
                .forEach(importName -> imports.append("import ").append(importName).append(";\n"));

        val code = render(TEMPLATE,
                "packageName", initClassPackage,
                "initClassName", initClassName,
                "className", className,
                "imports", imports.toString(),
                "constructorParams", constructorParams,
                "constructorAssignments", constructorAssignments
        );

        try {
            val sourceFile = processingEnv.getFiler()
                    .createSourceFile(initClassFullName, classElement);
            try (val writer = sourceFile.openWriter()) {
                writer.write(code);
                writer.flush();
            }
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "Generated: " + initClassFullName);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Failed to generate " + initClassFullName + ": " + e.getMessage());
        }
    }

    /**
     * 收集类内标注 {@code CAutowired} 的字段
     *
     * @param classElement 被注解的类元素
     * @return 字段信息列表，按类内声明顺序；无匹配字段时为空列表
     */
    private List<FieldInfo> findAutowiredFields(TypeElement classElement) {
        val fields = new ArrayList<FieldInfo>();
        for (val enclosed : classElement.getEnclosedElements()) {
            if (enclosed.getKind() == ElementKind.FIELD) {

                val field = (VariableElement) enclosed;
                val hasAutowired = field.getAnnotationMirrors().stream()
                        .anyMatch(am -> am.getAnnotationType().toString()
                                .equals(CAutowired.class.getCanonicalName()));
                if (hasAutowired) {
                    val fieldName = field.getSimpleName().toString();
                    val fieldType = field.asType().toString();
                    fields.add(new FieldInfo(fieldName, fieldType));
                }
            }
        }
        return fields;
    }

    /**
     * 取元素所属包名
     *
     * @param element 元素
     * @return 包名；元素不直接位于包下时返回空串
     */
    private String getPackageName(TypeElement element) {
        val enclosing = element.getEnclosingElement();
        if (enclosing.getKind() == ElementKind.PACKAGE) {
            return ((PackageElement) enclosing).getQualifiedName().toString();
        }
        return "";
    }

    /**
     * 以 {@code key,value} 成对入参替换模板中的 {@code ${key}} 占位符
     *
     * @param template 模板文本
     * @param kv       键值对，按 {@code key, value, key, value} 顺序传入
     * @return 替换后的文本
     */
    private String render(String template, String... kv) {
        String result = template;
        for (int i = 0; i < kv.length; i += 2) {
            val key = kv[i];
            val value = kv[i + 1];
            result = result.replace("${" + key + "}", value);
        }
        return result;
    }

    /**
     * 首字母大写
     *
     * @param str 原字符串
     * @return 首字母大写后的字符串；入参为 {@code null} 或空串时原样返回
     */
    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }

    /**
     * 将完整类型名（含泛型/数组）转为简单名类型声明，如：
     * java.util.List&lt;com.xxx.XxxService&gt; → List&lt;XxxService&gt;；com.xxx.Xxx[] → Xxx[]
     * 每个完整类名取其最后一个 '.' 之后的简单名（如 com.xxx.Xxx → Xxx）
     */
    private String toSimpleType(String fieldType) {
        return extractFullClassNames(fieldType).stream()
                .reduce(fieldType, (type, fullName) -> type.replace(
                        fullName, fullName.substring(fullName.lastIndexOf('.') + 1)));
    }

    /**
     * 提取类型字符串中的所有完整类名（含泛型参数、内嵌类），如：
     * java.util.Map&lt;java.lang.String, com.xxx.Xxx&gt; → [java.util.Map, java.lang.String, com.xxx.Xxx]
     */
    private List<String> extractFullClassNames(String fieldType) {
        val matcher = Pattern.compile("[a-zA-Z_$][a-zA-Z0-9_$]*(\\.[a-zA-Z_$][a-zA-Z0-9_$]*)+").matcher(fieldType);
        val names = new ArrayList<String>();
        while (matcher.find()) {
            names.add(matcher.group());
        }
        return names;
    }

    /**
     * 字段信息
     */
    private static class FieldInfo {
        /**
         * 字段名
         */
        final String fieldName;
        /**
         * 字段类型
         */
        final String fieldType;

        FieldInfo(String fieldName, String fieldType) {
            this.fieldName = fieldName;
            this.fieldType = fieldType;
        }
    }
}
